#!/bin/sh

FNAME=hash.py
HASHREF=https://raw.githubusercontent.com/nintendoapis/splatnet3-types/main/src/generated/latest.ts 

cat > $FNAME <<EOF
from enum import Enum

# See https://github.com/nintendoapis/splatnet3-types/blob/main/src/generated/latest.ts
# generated by $0

class SHA256Hash(Enum):
EOF

curl -s $HASHREF | cut -f5,8 -d ' ' | sed s,.\./,\ =\ \", | sed 's/\.js../\"/' | sed 's/^/        /' >> $FNAME

cat >> $FNAME <<EOF

EOF

